W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :index, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
   
  resource :session, only: [:new, :create, :destroy]
  resources :albums, only: [:create, :edit, :show, :update, :destroy]
end

W4D5/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :band_id, :title, :year, presence: true

  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band
end

W4D5/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    foreign_key: :band_id,
    class_name: :Album

end

W4D5/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true
  validates :email, :session_token, presence: true, uniqueness: true

  attr_reader :password
  after_initialize :ensure_session_token

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save
    self.session_token
  end

  def self.find_by_credentials(email, password)
    user = find_by(email: email)

    if user && user.is_password?(password)  #if the user exists and pw matches, return user
      user
    else
      nil
    end
  end

end

W4D5/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @bands = Band.all
  end

  def show

  end

  def edit
  end

  def create

  end

  def update

  end

  def destroy
    album = Album.find(params[:album][:id])
    album.destroy
  end

end

W4D5/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  #find by session token instead of params (email/pw)
  #find_by will query the db, assign inst. var to prevent querying multiple times
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
    # @current_user ||= User.find_by_credentials(params[:user][:email], params[:user][:password])
  end

  #returns boolean if someone is logged in
  def logged_in?
    !current_user.nil? 
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    session[:session_token] = nil
    if current_user
      @current_user.reset_session_token!
    end
    @current_user = nil
  end
end

W4D5/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def create
    band = Band.new(params[:id])
    if band.save
      redirect_to band_url(band)
    else
      flash[:errors] = band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    @band.name = params[:band][:name]
    @band.save
    redirect_to band_url(@band)
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end
end

W4D5/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ['Invalid Credentials']
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end


end

W4D5/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def new
  end

  def create
    user = User.new(user_params)

    if user.save
      log_in_user!(user)
      redirect_to user_url(user)   #redirect to their specific page
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def index
    @users = User.all
    render :index
  end

  def show
    user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

  def require_login
    redirect_to new_user_url unless current_user
  end
end

W4D5/music_app/app/views/albums/_album_form.html.erb
<div class="new_album">
  <form action="<%= action_url %>" method="post">
    <input type="hidden" name="_method" value="<%= method %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
      Title:
      <input type="text" name="albums[title]">
    </label>
    <br>
    <label>
      Band:

        <select>
          <% @bands.each do |band| %>
          <option value="">  <%= band.name %>  </option>
          <% end %>
        </select>
    </label>
    <br>
    <label>
      <input type="radio" name="album[live]" value="live"> <label for="live_album"> Live </label>
      <input type="radio" name="album[live]" value="studio"> <label for="studio_album"> Studio </label>
    </label>
  <br>
    <label>
      Year:
      <input type="text" name="album[year]" value="">
    </label>
  </form>
</div>

W4D5/music_app/app/views/albums/edit.html.erb
<%= render 'album_form', action_url: album_url(@album), method: :patch %>

W4D5/music_app/app/views/albums/new.html.erb
<%= render 'album_form', action_url: albums_url, method: :post %>

W4D5/music_app/app/views/albums/show.html.erb
<h3> Album:  </h3>

<% @albums.each do |album| %>
 <p> <%= album %> </p>
<h4> Links </h4>

<a href="<%= band_url(@band) %>"> Back to band </a>
<br>
<a href="<%= album_url(@album) %>"> View Tracks (coming soon...) </a>
<br>
<a href="<%= bands_url %>"> All Albums </a>
<br>
<form action="<%= album_url(@album)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Destroy Album">
</form>

W4D5/music_app/app/views/bands/_band_form.html.erb
<h3> Add a new band </h3>

  <form class="new_band" action="<%= new_band_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
      Name of band:
      <input type="text" name="band[name]">
      <input type="submit" name="" value=" Submit ">
    </label>
  </form>

W4D5/music_app/app/views/bands/edit.html.erb
<h3> Edit <%= @band.name %> </h3>
<form class="new_band" action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    New name:
    <input type="text" name="band[name]">
    <input type="submit" name="" value=" Submit ">
  </label>
</form>

<br>
<h4> Links </h4>
<br>
<a href="<%= bands_url %>"> All Bands </a>

W4D5/music_app/app/views/bands/index.html.erb
<p> This is the home page for ALL bands </p>
<br>
<h4> Links </h4>
<a href="<%= new_band_url %>"> New Band </a>
<br>
<br>
<% @bands.each do |band| %>

<div class="band_container">
  <div class="band_pics">
    <img src="https://upload.wikimedia.org/wikipedia/en/thumb/2/23/Backstreetboysbsb_lp01.jpg/220px-Backstreetboysbsb_lp01.jpg" alt="">
    <br>
    <a href="<%= band_url(band) %>"> <%= band.name %> </a>  <!-- This should take us to a single band's page-->
  </div>
</div>


<% end %>

W4D5/music_app/app/views/bands/new.html.erb
<h3> Add a new band </h3>

  <form class="new_band" action="<%= new_band_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
      Name of band:
      <input type="text" name="band[name]">
      <input type="submit" name="" value=" Submit ">
    </label>
  </form>

<br>
<h4> Links </h4>
<br>
<a href="<%= bands_url %>"> All Bands </a>

W4D5/music_app/app/views/bands/show.html.erb
<h3><%= @band.name %></h3>

<br>

<div class="albums">
  <h4> Albums </h4>
  <p> No albums yet...</p>
</div>
<br>

<h4> Links </h4>

<a href="<%= new_band_album_url(@band) %>"> New Album </a>
<br>
<a href="<%= edit_band_url(@band) %>"> Edit Band </a>
<br>
<a href="<%= bands_url %>"> All Bands </a>
<br>
<form action="<%= band_url(@band)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Destroy Band">
</form>

W4D5/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Music App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Advent+Pro" rel="stylesheet">

  </head>

  <body>
    <h1>MUSIC APP</h1>
    <div class="log_in_sign_in">
      <a href="<%= new_session_url %>"> Log-In </a>
      <a href="<%= new_user_url %>"> Sign-Up </a>
    </div>
    <br>
    <%= yield %>
  </body>
</html>

W4D5/music_app/app/views/users/_user_form.html.erb
<form action='<%= action_url %>' method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label>
  Email:
  <input type="text" id="email" name="user[email]">
</label>
<br>
<label>
  Password:
  <input type="password" id="password" name="user[password]">
</label>

<br>
<input type="submit" name="" value="<%= submit_type %>">

<% if flash.now[:errors] %>
   <% flash.now[:errors].each do |error| %>
     <%= error %>
   <% end %>
 <% end %>

</form>

W4D5/music_app/app/views/users/index.html.erb
<h3> Welcome to Music App </h3>

<br>
<br>
<br>
<br>
<br>

<p> THIS IS THE HOME PAGE </p>

W4D5/music_app/app/views/users/new.html.erb
<!-- sign-up page  -->

<%= render 'user_form', action_url: users_url, submit_type: 'Sign-Up!'%>

W4D5/music_app/app/views/users/show.html.erb
<h3> Welcome to Music App </h3>
<br>

<a href="<%=bands_url%>"> Check out the bands </a>

<p> THIS IS THE INDIVIDUAL USER'S PAGE! </p>
<br>

<form action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Logout">
</form>